### ISSUE TITLE
Unable to link downstream project consuming Kotlin/Native-built runtime

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/compose-multiplatform#2342]
```
> Task :molecule-runtime:linkDebugTestIosSimulatorArm64 FAILED
e: Compilation failed: Failed to compute the detailed error message. See the root cause exception.

Shortly: The required symbol androidx.compose.runtime/remember|-4100818973694024771[0] is missing in the module or module dependencies. This could happen if the required dependency is missing in the project. Or if there is a dependency that has a different version (without the required symbol) in the project than the version (with the required symbol) that the module was initially compiled with.
```

I have `kotlin.native.cacheKind=none` set in the project's `gradle.properties` but it still does not compile.

Repro on this branch https://github.com/cashapp/molecule/tree/jw/link-thing/2022-09-21 running `./gradlew -p molecule :m-r:check`.

**Comment by dima-avdeev-jb** [comment]
I will research

**Comment by kirillzh** [comment]
`kotlin.native.cacheKind=none` doesn't do anything for me, but seems to help `kotlin.native.cacheKind.iosArm64=none` (I am on M1).

**Comment by dima-avdeev-jb** [comment]
I reproduced this problem with iosSimulatorArm64Test task. I will continue try to fix it.

But also, for now, you may use only jvm tests: ```./gradlew -p molecule :m-r:jvmTest```

**Comment by DjakaTechnology** [comment]
I can reproduce this, also happens when building to an iOS app target not just testing only. I can't use compose runtime in shared module because of this.

**Comment by dima-avdeev-jb** [comment]
> I can reproduce this, also happens when building to an iOS app target not just testing only. I can't use compose runtime in shared module because of this.

Thanks! I will research your sample

**Comment by JakeWharton** [comment]
You are correct we are not specifying the JS option correctly. Molecule's multiplatform entrance is a little more rash than Redwood where we did things a bit more carefully. That being said, we cannot use your Compose plugin because it assumes things about the JS target (the presence of a web extension) that doesn't work in the general case.

In Redwood we have a proper subproject plugin which applies the Compose compiler plugin and configures the JS build correctly: https://github.com/cashapp/redwood/blob/3956a7883950951f38e5d0c442d63b32cdfc955f/build-support/src/main/kotlin/app/cash/redwood/buildsupport/ComposePlugin.kt. I will do the same in Molecule here shortly.

**Comment by saket** [comment]
I was also able to fix this specific issue by upgrading to Kotlin 1.7.20, but ended up running into another wall:

```
e: Compilation failed: Unbound symbols not allowed

Unbound public symbol IrSimpleFunctionPublicSymbolImpl: me.saket.teleport.ui/Presenter.present|-8951064700938915987[0]

 * Source files:
 * Compiler version info: Konan: 1.7.20 / Kotlin: 1.7.20
 * Output kind: FRAMEWORK

e: java.lang.AssertionError: Unbound symbols not allowed
```

@JakeWharton Do you still have your `jw/link-thing/2022-09-21` branch around? I'd like to compare my setup with yours.

**Comment by hfhbd** [comment]
@saket Did you add `kotlin.native.cacheKind=none`? I got the same error and this resolved it.

**Comment by saket** [comment]
Yea I already had `kotlin.native.cacheKind=none` in my `gradle.properties` so I believe I'm running into something else. Do you have a public project that I can take a look at?

**Comment by hfhbd** [comment]
I have a current work-in-progress pr to include molecule into my playground app: https://github.com/hfhbd/ComposeTodo/pull/665/files

I had to add the molecule runtime manually though, because I also use the compose plugin: https://github.com/cashapp/molecule/issues/134

**Comment by dima-avdeev-jb** [comment]
@saket Can you please try version **1.3.0-alpha01-dev849**
with kotlin.native.cacheKind=non

**Comment by saket** [comment]
Sure, where are your alpha builds hosted on? I couldn't find any information in your readme or releases page.

**Comment by saket** [comment]
@hfhbd going through this, thank you!

**Comment by dima-avdeev-jb** [comment]
@saket 
You need set repository here:
https://github.com/JetBrains/compose-jb/blob/master/experimental/examples/falling-balls-mpp/settings.gradle.kts#L6
and here: 
https://github.com/JetBrains/compose-jb/blob/master/experimental/examples/falling-balls-mpp/build.gradle.kts#L20

**Comment by saket** [comment]
Thanks! I'm seeing the same error with `1.3.0-alpha01-dev849`.

**Comment by mateuyabar** [comment]
@saket I had the same error in my case when using molecule. Its was caused due that composable functions couldn't be public in native (at least this is what I've read). I fixed it changing them to internal (an in my case only expose the flow created by the molecule launch)

**Comment by dima-avdeev-jb** [comment]
@saket 
Yeah, for now Composable functions for native can be only internal or private. We will fix it in the future.

**Comment by Nailik** [comment]
> @saket Yeah, for now Composable functions for native can be only internal or private. We will fix it in the future.

Did this change or is this still valid?

**Comment by eymar** [comment]
@Nailik 
> for now Composable functions for native can be only internal or private. We will fix it in the future.

This part is fixed when using kotlin 1.8.20 and compose 1.4.0
___

kotlin.native.cacheKind=none - this parameter is still needed. The investigation has started by k/native team

**Comment by Nailik** [comment]
> @Nailik
> 
> > for now Composable functions for native can be only internal or private. We will fix it in the future.
> 
> This part is fixed when using kotlin 1.8.20 and compose 1.4.0
> 
> kotlin.native.cacheKind=none - this parameter is still needed. The investigation has started by k/native team

Unfortunately i still get error: `Module "Rhasspy_Mobile:ui" has a reference to symbol androidx.compose.runtime/CompositionLocalProvider|1991010962478225151[0]. Neither the module itself nor its dependencies contain such declaration. ` with this project https://github.com/Nailik/rhasspy_mobile/tree/1454949c0d42b60ce48dc57ffb446e4061531522

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2342">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
