### ISSUE TITLE
Invoking the skiko library causes runtime error on windows

### ISSUE THREAD

**Issue by YasserDbeis** [JetBrains/compose-multiplatform#3243]
**Describe the bug**
I am an engineer for Android Studio and when utilizing compose desktop in our code base, the skiko rendering library works fine on a native windows computer. However, when running junit4 tests for compose desktop, which invoke the skiko rendering library, the following runtime error occurs. 

`C:\Users\ContainerAdministrator\.skiko\063b343873479b9f89de391312b12e17f62d6f4aaa9cbdcef6c1a225561c1e66\skiko-windows-x64.dll: Can't find dependent libraries
java.lang.UnsatisfiedLinkError: C:\Users\ContainerAdministrator\.skiko\063b343873479b9f89de391312b12e17f62d6f4aaa9cbdcef6c1a225561c1e66\skiko-windows-x64.dll: Can't find dependent libraries
    at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
    at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
    at java.base/java.lang.Runtime.load0(Runtime.java:755)
    at java.base/java.lang.System.load(System.java:1953)
    at org.jetbrains.skiko.Library.loadLibraryOrCopy(Library.kt:20)
    at org.jetbrains.skiko.Library.findAndLoad(Library.kt:113)
    at org.jetbrains.skiko.Library.load(Library.kt:59)
    at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
    at org.jetbrains.skia.Surface.<clinit>(Surface.kt:539)
    at androidx.compose.ui.test.SkikoComposeUiTest.<init>(ComposeUiTest.skikoMain.kt:118)
    at androidx.compose.ui.test.SkikoComposeUiTest.<init>(ComposeUiTest.skikoMain.kt:72)
    at androidx.compose.ui.test.junit4.DesktopComposeTestRule.<init>(DesktopComposeTestRule.desktop.kt:42)
    at androidx.compose.ui.test.junit4.DesktopComposeTestRule_desktopKt.createComposeRule(DesktopComposeTestRule.desktop.kt:34)
    at com.android.tools.idea.compose.test.SampleComposeComponentTest.<init>(SampleComposeComponentTest.kt:31)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
    at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:306)
    at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
)`

Investigating futher into this bug, I found that the skiko-windows-x64.dll was on the classpath and thus on the CI computer. Knowing this, I looked deeper to see what the dependencies of this dll are and found the following: 
ADVAPI32.dll
GDI32.dll
dwmapi.dll
OPENGL32.dll
USER32.dll
KERNEL32.dll

I checked to see if each was on the classpath and thus on the device and found that the OPENGL32.dll is not present on the CI machine. However, from my understanding, it should fallback to some other library and not just fail. Speaking with people on the Compose team in Google, it was said that "the intention has always been to fallback to software rendering automatically if opengl is not found, it sounds like somehow there is a bug in the automatic fallback logic.".

Changing env vars and/or adding dlls/libraries, or really any modifications to the CI computer is not a feasible option/solution.
 
**Affected platforms**
- Desktop (Windows only)

**Versions**
- Kotlin version*: 1.6 (1.8.21 compiler)
- Compose Multiplatform version*: 1.3.1
- OS version(s)* (required for Desktop and iOS issues): Windows 10
- OS architecture (x86 or arm64):  x86
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
[Included in bug description, but one direct way is to invoke the createComposeRule method located at androidx.compose.ui.test.junit4.createComposeRule. This will trigger the runtime error on windows devices with no OPENGL32.dll dependency and failing fallback logic].

**Expected behavior**
No error

**Screenshots**

**Additional context**

**Comment by YasserDbeis** [comment]
Also worth noting that the skiko version is 0.7.55.

**Comment by Burtan** [comment]
I'm having the same problem with docker based ci environments that don't have an ui stack.

**Comment by YasserDbeis** [comment]
Any update on this?

**Comment by YasserDbeis** [comment]
Sounds good. Thank you!

**Comment by YasserDbeis** [comment]
What version of compose multi-platform will this land?

**Comment by igordmn** [comment]
It will be in 1.5.10 Stable, and in a dev version in a 1-2 days

**Comment by igordmn** [comment]
It should be fixed in 1.5.10-rc01. Could you check?

**Comment by YasserDbeis** [comment]
I have tried this with 1.5.10 stable and it is still failing. I am using skiko 0.7.77, should I be using another version?

**Comment by igordmn** [comment]
>  I am using skiko 0.7.77, should I be using another version?

Yes, it should be 0.7.85, the fix was in skiko

**Comment by YasserDbeis** [comment]
It is not failing anymore on windows--thank you!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3243">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
