### ISSUE TITLE
Keyboard `done` action behaves differently on Android and on iOS

### ISSUE THREAD

**Issue by marenovakovic** [JetBrains/compose-multiplatform#3473]
**Describe the bug**
Keyboard `done` action works differently on Android and iOS.
On Android it's doing what's it supposed to.
On iOS it adds `\n` at the end of `TextField` text.

**Affected platforms**
Select one of the platforms below:
- Android
- iOS

**Versions**
- Kotlin version*: 1.9.0
- Compose Multiplatform version*: 1.5.0-beta01
- OS version(s)*: iOS 16.4, Android 13
- OS architecture : arm64

**To Reproduce**
Steps and/or the code snippet to reproduce the behaviour:
Try `done` action.

**Expected behaviour**
iOS should behave same as Android.

**Screenshots**

[wdwl-android-keyboard-done-action.webm](https://github.com/JetBrains/compose-multiplatform/assets/29804184/fed6ca92-c888-42b7-930a-7d84eb51f0c8)

https://github.com/JetBrains/compose-multiplatform/assets/29804184/6063fef5-f5c9-4bb3-9b17-1253e2b5adcd

**Comment by elijah-semyonov** [comment]
Thanks for reporting the issue.

@dima-avdeev-jb can you have a look at it?

**Comment by Aidanvii7** [comment]
facing the same issue, this is a bit of a blocker for me, I can't see any obvious workarounds 😕

**Comment by alexeiartsimovich** [comment]
I have the same issue and it's a major blocker since one of the main features of my app is chat. Any workaround is appreciated

**Comment by Aidanvii7** [comment]
> I have the same issue and it's a major blocker since one of the main features of my app is chat. Any workaround is appreciated

You could try something like this if you consider it illegal to have `\n` in the chat:
```kotlin
val keyboardController: SoftwareKeyboardController? = LocalSoftwareKeyboardController.current
val textState = remember { mutableStateOf("") }
TextField(
    value = textState.value,
    onValueChange = { newText: String ->
        if (newText.endsWith('\n')) {
            keyboardController?.hide()
        } else {
            textState.value = newText
        }
    },
)
```

I haven't tested this, however it does't work in the case of a password field which could contain that character, making login screens very difficult atm 😕

**Comment by jamesmbowler** [comment]
Looks fixed in 1.5.1 🤷

**Comment by dima-avdeev-jb** [comment]
@mazunin-v-jb Can you please check and close if it is alread done in 1.5.1 ?

**Comment by DasJhaman** [comment]
Still not fixed, I am using 1.5.10-beta01 but I still have the same issue. There is no way to close the keyboard with a number pad.

**Comment by marenovakovic** [comment]
my app doesn't work on iOS with compose version 1.5.1.
everything works fine on `1.5.10-beta01`.
there is different issue now, text edit field label is cut off on the top. but that's another issue.

**Comment by mazunin-v-jb** [comment]
@dima-avdeev-jb, works as expected now.
https://github.com/JetBrains/compose-multiplatform/assets/124871594/a9f5adc4-4d51-48b9-b23b-ce3be9c5e3d8

**Comment by mazunin-v-jb** [comment]
@marenovakovic, please, feel free to create a new issue for a new problem.
And to reopen that one if that problem is still not fixed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3473">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
