### ISSUE TITLE
CMPViewControllerMisuse error introduced in Compose 1.6.0-beta01

### ISSUE THREAD

**Issue by brendanw** [JetBrains/compose-multiplatform#4188]
**Describe the bug**
A `CMPViewControllerMisuse` error is thrown for a case where it wasn't in compose `1.5.11`.

```
'CMPViewControllerMisuse', reason: 'CMPViewController shouldn't be reused after completely removed from hierarchy, because it's logically marked as Destroyed. You must create a new CMPViewController and use it instead.'
```

**Affected platforms**
Select one of the platforms below:
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0-beta01
- OS version(s)* (required for Desktop and iOS issues): 17.2.1
- OS architecture (x86 or arm64): arm64

**To Reproduce**"
You can reproduce the code using the code from the old template on this branch -> https://github.com/brendanw/compose-multiplatform-template/pull/2

1. Launch an ios app that has a single viewcontroller that is a `ComposeUIViewController`
2. From within that `ComposeUIViewController` call `present` to present a `AVPlayerViewController`
3. turn off the device screen
4. turn on the device screen
5. back navigate out of the `AVPlayerViewController`

**Expected behavior**
No `CMPViewControllerMisuse` error should be thrown.

**Screenshots**
![2024-01-26 19 38 03](https://github.com/JetBrains/compose-multiplatform/assets/585321/b9b732ac-bc26-48d8-a9dc-d1b186cf5d64)

**Additional context**
N/A

**Comment by elijah-semyonov** [comment]
It's reproduced even without the sending the app to background.

**Comment by elijah-semyonov** [comment]
Fixed in https://github.com/JetBrains/compose-multiplatform-core/pull/1027

**Comment by Kashif-E** [comment]
this is still occurring in 1.6.11 and I am able to reproduce this in 1.6.2

**Comment by ahmedsalemelzeiny** [comment]
this is still occurring on the latest versions, @Kashif-E did you find a solution for it?

**Comment by elijah-semyonov** [comment]
Please, post a repro, it should have been fixed.

**Comment by Shamyyoun** [comment]
@ahmedsalemelzeiny @elijah-semyonov 
Verified it again and it's fixed yeah. The issue was that we were using a view controller wrapper in iOS to avoid disposing the compose view controller (old issue) but no need for it now and after removing it everything is working fine 🥳🥳🥳

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4188">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by omargda** [comment]
Hello, I also ran into the same error while using Kotlin version `1.9.22` and Compose Multiplatform version `1.5.11`. Which Compose Multiplatform version was the fix introduced? Is it one compatible with Kotlin version `1.9.22`? I'm not currently able to go to a higher Kotlin version. Thanks!
