### ISSUE TITLE
findNextNonWhitespaceSymbolsSubsequenceStartOffset crash

### ISSUE THREAD

**Issue by brendanw** [JetBrains/compose-multiplatform#4531]
**Describe the bug**
App crashes upon textfield usage.

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): 17.4.1
- Device (model or simulator for iOS issues): iphone 15.2

**To Reproduce**
No reproduction steps. This is a crash report observed via bugsnag in the wild. Does not happen often. Hoping the team the team can use the stacktrace to deduce the issue+solution.

```
kotlin.ArrayIndexOutOfBoundsException: 

0  BaseBetaiOS +0x4bbfc     kfun:kotlin.Throwable#<init>(){} (Throwable.kt:32:21)
1  BaseBetaiOS +0xd5a808    Kotlin_String_get
2  BaseBetaiOS +0x566be4    kfun:androidx.compose.foundation.text#codePointAt__at__kotlin.CharSequence(kotlin.Int){}kotlin.Int (StringHelpers.skiko.kt:70:16)
3  BaseBetaiOS +0x564f28    kfun:androidx.compose.foundation.text#findNextNonWhitespaceSymbolsSubsequenceStartOffset(kotlin.Int;kotlin.String){}kotlin.Int (StringHelpers.skiko.kt:127:83)
4  BaseBetaiOS +0x8fa7d0    kfun:kotlin.Function1#invoke(1:0){}1:1-trampoline ([K][Suspend]Functions:1:1)
5  BaseBetaiOS +0x562a1c    kfun:androidx.compose.foundation.gestures.$detectRepeatingTapGestures$lambda$0COROUTINE$0.invokeSuspend#internal (TapGesturesDetector.skiko.kt)
6  BaseBetaiOS +0x39268     kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#invokeSuspend(kotlin.Result<kotlin.Any?>){}kotlin.Any?-trampoline (ContinuationImpl.kt:50:24)
7  BaseBetaiOS +0xf0034     kfun:kotlinx.coroutines#resume__at__kotlinx.coroutines.DispatchedTask<0:0>(kotlin.coroutines.Continuation<0:0>;kotlin.Boolean){0§<kotlin.Any?>} (DispatchedTask.kt)
8  BaseBetaiOS +0xbbd20     kfun:kotlinx.coroutines#dispatch__at__kotlinx.coroutines.DispatchedTask<0:0>(kotlin.Int){0§<kotlin.Any?>} (DispatchedTask.kt:164:9)
9  BaseBetaiOS +0xbc238     <inlined-out:<anonymous>> (CancellableContinuationImpl.kt:504:21)
10 BaseBetaiOS +0xbb39c     kfun:kotlinx.coroutines.CancellableContinuationImpl#resumeImpl$default(kotlin.Any?;kotlin.Int;kotlin.Function1<kotlin.Throwable,kotlin.Unit>?;kotlin.Int){} (CancellableContinuationImpl.kt:493:13)
11 BaseBetaiOS +0x3a9e14    <inlined-out:resume> (Continuation.kt:45:5)
12 BaseBetaiOS +0x3a8c44    <inlined-out:<anonymous>> (SuspendingPointerInputFilter.kt:549:16)
13 BaseBetaiOS +0x3a8f10    kfun:androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl#onPointerEvent(androidx.compose.ui.input.pointer.PointerEvent;androidx.compose.ui.input.pointer.PointerEventPass;androidx.compose.ui.unit.IntSize){} (SuspendingPointerInputFilter.kt:571:9)
14 BaseBetaiOS +0x3a1fa4    <inlined-out:<anonymous>> (HitPathTracker.kt:326:24)
15 BaseBetaiOS +0x3a1f10    <inlined-out:<anonymous>> (HitPathTracker.kt:312:24)
16 BaseBetaiOS +0x3a1f10    <inlined-out:<anonymous>> (HitPathTracker.kt:312:24)
17 BaseBetaiOS +0x3a1f10    <inlined-out:<anonymous>> (HitPathTracker.kt:312:24)
18 BaseBetaiOS +0x3a1f10    <inlined-out:<anonymous>> (HitPathTracker.kt:312:24)
19 BaseBetaiOS +0x3a144c    <inlined-out:<anonymous>> (HitPathTracker.kt:187:29)
20 BaseBetaiOS +0x40cb84    kfun:androidx.compose.ui.input.pointer.NodeParent#dispatchMainEventPass(androidx.collection.LongSparseArray<androidx.compose.ui.input.pointer.PointerInputChange>;androidx.compose.ui.layout.LayoutCoordinates;androidx.compose.ui.input.pointer.InternalPointerEvent;kotlin.Boolean){}kotlin.Boolean-trampoline (HitPathTracker.kt:179:10)
21 BaseBetaiOS +0x420a3c    kfun:androidx.compose.ui.scene.SingleLayerComposeSceneImpl.processPointerInputEvent#internal (SingleLayerComposeScene.skiko.kt:162:19)
22 BaseBetaiOS +0x4184dc    kfun:androidx.compose.ui.scene.BaseComposeScene#processPointerInputEvent(androidx.compose.ui.input.pointer.PointerInputEvent){}-trampoline (BaseComposeScene.skiko.kt:230:24)
23 BaseBetaiOS +0x8fa7d0    kfun:kotlin.Function1#invoke(1:0){}1:1-trampoline ([K][Suspend]Functions:1:1)
24 BaseBetaiOS +0x409f40    kfun:androidx.compose.ui.input.pointer.SyntheticEventSender.sendInternal#internal (SyntheticEventSender.skiko.kt:175:9)
25 BaseBetaiOS +0x419388    kfun:androidx.compose.ui.input.pointer.SyntheticEventSender#send(androidx.compose.ui.input.pointer.PointerInputEvent){} (SyntheticEventSender.skiko.kt:79:9)
26 BaseBetaiOS +0x4180a0    <inlined-out:<anonymous>> (BaseComposeScene.skiko.kt:207:22)
27 BaseBetaiOS +0x44ae80    kfun:androidx.compose.ui.scene.ComposeScene#sendPointerEvent(androidx.compose.ui.input.pointer.PointerEventType;kotlin.collections.List<androidx.compose.ui.scene.ComposeScenePointer>;androidx.compose.ui.input.pointer.PointerButtons;androidx.compose.ui.input.pointer.PointerKeyboardModifiers;androidx.compose.ui.geometry.Offset;kotlin.Long;kotlin.Any?;androidx.compose.ui.input.pointer.PointerButton?){}-trampoline (ComposeScene.skiko.kt:212:5)
28 BaseBetaiOS +0x45f21c    <inlined-out:<anonymous>> (InteractionUIView.uikit.kt:96:29)
29 BaseBetaiOS +0xd2858c    _6f72672e6a6574627261696e732e636f6d706f73652e75693a75692f6f70742f6275696c644167656e742f776f726b2f383339343731666333323931333563372f636f6d706f73652f75692f75692f7372632f75696b69744d61696e2f6b6f746c696e2f616e64726f6964782f636f6d706f73652f75692f77696e646f772f496e746572616374696f6e5549566965772e75696b69742e6b74_kncfun45
30 UIKitCore +0x201318      -[UIWindow _sendTouchesForEvent:]
31 UIKitCore +0x200e60      -[UIWindow sendEvent:]
32 UIKitCore +0x2000e0      -[UIApplication sendEvent:]
33 UIKit +0x4fbd8           -[UIApplicationAccessibility sendEvent:]
```

**Expected behavior**
No crash

**Additional context**
```
CrashReporter Key:  3f3320d67ac3c3692e7674efa051044837971959
Hardware Model:     iPhone15,2
Version:            2024.1.110
Role:               Foreground
OS Version:         iOS 17.4.1
```

**Comment by zacharee** [comment]
Seeing the same crash, ranging from iOS 14.3.1 to 17.4.

Compose 1.6.1, Compiler 1.5.8.1, Kotlin 1.9.23.

**Comment by mazunin-v-jb** [comment]
Should be fixed in 1.6.2

**Comment by VdBarros** [comment]
Still happening in 1.6.5.

stackTrace:

`#0	0x102659e00 in ThrowArrayIndexOutOfBoundsException ()
#1	(null) in Kotlin_String_get ()
#2	0x102a0ab58 in kfun:androidx.compose.foundation.text#codePointAt__at__kotlin.CharSequence(kotlin.Int){}kotlin.Int ()
#3	0x102a08e9c in kfun:androidx.compose.foundation.text#findNextNonWhitespaceSymbolsSubsequenceStartOffset(kotlin.Int;kotlin.String){}kotlin.Int ()
#4	0x102a08e9c in kfun:androidx.compose.foundation.text#determineCursorDesiredOffset(kotlin.Int;androidx.compose.ui.text.input.TextFieldValue;androidx.compose.foundation.text.TextLayoutResultProxy;kotlin.String){}ko... ()
#5	0x102a08e9c in kfun:androidx.compose.foundation.text#cupertinoSetCursorOffsetFocused__at__androidx.compose.foundation.text.TextFieldDelegate.Companion(androidx.compose.ui.geometry.Offset;androidx.compose.foundati... ()
#6	0x102a08e9c in <inlined-out:<anonymous>> ()
#7	0x102a08e9c in <inlined-out:let> ()
#8	0x102a08e9c in kfun:androidx.compose.foundation.text.getTapHandlerModifier$lambda$16$lambda$13#internal ()
#9	0x102a08e9c in kfun:androidx.compose.foundation.text.$getTapHandlerModifier$lambda$16$lambda$13$FUNCTION_REFERENCE$7.invoke#internal ()
#10	0x102a08e9c in kfun:androidx.compose.foundation.text.$getTapHandlerModifier$lambda$16$lambda$13$FUNCTION_REFERENCE$7.$<bridge-UNNB>invoke(androidx.compose.ui.geometry.Offset){}#internal ()
#11	0x102dd9a18 in kfun:kotlin.Function1#invoke(1:0){}1:1-trampoline ()
#12	(null) in kfun:androidx.compose.foundation.gestures.$detectRepeatingTapGestures$lambda$0COROUTINE$0.invokeSuspend#internal ()
#13	0x1026464f8 in kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#invokeSuspend(kotlin.Result<kotlin.Any?>){}kotlin.Any?-trampoline ()
#14	0x1026464f8 in <inlined-out:<anonymous>> ()
#15	0x1026464f8 in <inlined-out:with> ()
#16	0x1026464f8 in kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} ()
#17	(null) in kfun:kotlinx.coroutines#resume__at__kotlinx.coroutines.DispatchedTask<0:0>(kotlin.coroutines.Continuation<0:0>;kotlin.Boolean){0§<kotlin.Any?>} ()
#18	0x1026c64b0 in kfun:kotlinx.coroutines#dispatch__at__kotlinx.coroutines.DispatchedTask<0:0>(kotlin.Int){0§<kotlin.Any?>} ()
#19	0x1026c64b0 in kfun:kotlinx.coroutines.CancellableContinuationImpl.dispatchResume#internal ()
#20	0x1026c69c8 in <inlined-out:<anonymous>> ()
#21	(null) in <inlined-out:loop$atomicfu> ()
#22	(null) in kfun:kotlinx.coroutines.CancellableContinuationImpl.resumeImpl#internal ()
#23	0x1026c5b2c in kfun:kotlinx.coroutines.CancellableContinuationImpl#resumeImpl$default(kotlin.Any?;kotlin.Int;kotlin.Function1<kotlin.Throwable,kotlin.Unit>?;kotlin.Int){} ()
#24	0x1026c5b2c in kfun:kotlinx.coroutines.CancellableContinuationImpl#resumeWith(kotlin.Result<1:0>){} ()
#25	0x10287cae8 in <inlined-out:resume> ()
#26	0x10287cae8 in <inlined-out:<anonymous>> ()
#27	0x10287cae8 in <inlined-out:run> ()
#28	0x10287cae8 in kfun:androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.PointerEventHandlerCoroutine.offerPointerEvent#internal ()
#29	0x10287b918 in <inlined-out:<anonymous>> ()
#30	0x10287b918 in <inlined-out:forEachReversed> ()
#31	0x10287b918 in <inlined-out:forEachCurrentPointerHandler> ()
#32	0x10287b918 in kfun:androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent#internal ()
#33	0x10287bbe4 in kfun:androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl#onPointerEvent(androidx.compose.ui.input.pointer.PointerEvent;androidx.compose.ui.input.pointer.PointerEventPass;androi... ()
#34	0x102874de8 in <inlined-out:<anonymous>> ()
#35	0x102874de8 in <inlined-out:dispatchForKind> ()
#36	0x102874de8 in <inlined-out:<anonymous>> ()
#37	0x102874de8 in <inlined-out:dispatchIfNeeded> ()
#38	0x102874de8 in kfun:androidx.compose.ui.input.pointer.Node#dispatchMainEventPass(androidx.collection.LongSparseArray<androidx.compose.ui.input.pointer.PointerInputChange>;androidx.compose.ui.layout.LayoutCoordina... ()
#39	0x102874d54 in <inlined-out:<anonymous>> ()
#40	0x102874d54 in <inlined-out:forEach> ()
#41	0x102874d54 in <inlined-out:<anonymous>> ()
#42	0x102874d54 in <inlined-out:dispatchIfNeeded> ()
#43	0x102874d54 in kfun:androidx.compose.ui.input.pointer.Node#dispatchMainEventPass(androidx.collection.LongSparseArray<androidx.compose.ui.input.pointer.PointerInputChange>;androidx.compose.ui.layout.LayoutCoordina... ()
#44	0x1028742a0 in <inlined-out:<anonymous>> ()
#45	0x1028742a0 in <inlined-out:forEach> ()
#46	0x1028742a0 in kfun:androidx.compose.ui.input.pointer.NodeParent#dispatchMainEventPass(androidx.collection.LongSparseArray<androidx.compose.ui.input.pointer.PointerInputChange>;androidx.compose.ui.layout.LayoutCo... ()
#47	0x1028df6f8 in kfun:androidx.compose.ui.input.pointer.NodeParent#dispatchMainEventPass(androidx.collection.LongSparseArray<androidx.compose.ui.input.pointer.PointerInputChange>;androidx.compose.ui.layout.LayoutCo... ()
#48	0x1028df6f8 in kfun:androidx.compose.ui.input.pointer.HitPathTracker#dispatchChanges(androidx.compose.ui.input.pointer.InternalPointerEvent;kotlin.Boolean){}kotlin.Boolean ()
#49	0x1028df6f8 in kfun:androidx.compose.ui.input.pointer.PointerInputEventProcessor#process(androidx.compose.ui.input.pointer.PointerInputEvent;androidx.compose.ui.input.pointer.PositionCalculator;kotlin.Boolean){}a... ()
#50	0x1028df6f8 in kfun:androidx.compose.ui.node.RootNodeOwner#onPointerInput(androidx.compose.ui.input.pointer.PointerInputEvent){} ()
#51	0x1028f34e0 in kfun:androidx.compose.ui.scene.SingleLayerComposeSceneImpl.processPointerInputEvent#internal ()
#52	0x1028eb024 in kfun:androidx.compose.ui.scene.BaseComposeScene#processPointerInputEvent(androidx.compose.ui.input.pointer.PointerInputEvent){}-trampoline ()
#53	0x1028eb024 in kfun:androidx.compose.ui.scene.BaseComposeScene.$processPointerInputEvent$FUNCTION_REFERENCE$5.invoke#internal ()
#54	0x1028eb024 in kfun:androidx.compose.ui.scene.BaseComposeScene.$processPointerInputEvent$FUNCTION_REFERENCE$5.$<bridge-UNNN>invoke(androidx.compose.ui.input.pointer.PointerInputEvent){}#internal ()
#55	0x102dd9a18 in kfun:kotlin.Function1#invoke(1:0){}1:1-trampoline ()
#56	0x1028dc86c in kfun:androidx.compose.ui.input.pointer.SyntheticEventSender.sendInternal#internal ()
#57	0x1028ebed0 in kfun:androidx.compose.ui.input.pointer.SyntheticEventSender#send(androidx.compose.ui.input.pointer.PointerInputEvent){} ()
#58	0x1028ebed0 in kfun:androidx.compose.ui.scene.ComposeSceneInputHandler#onPointerEvent(androidx.compose.ui.input.pointer.PointerEventType;kotlin.collections.List<androidx.compose.ui.scene.ComposeScenePointer>;andr... ()
#59	0x1028eabe8 in <inlined-out:<anonymous>> ()
#60	0x1028eabe8 in <inlined-out:performSnapshotChangesSynchronously> ()
#61	0x1028eabe8 in <inlined-out:postponeInvalidation> ()
#62	0x1028eabe8 in kfun:androidx.compose.ui.scene.BaseComposeScene#sendPointerEvent(androidx.compose.ui.input.pointer.PointerEventType;kotlin.collections.List<androidx.compose.ui.scene.ComposeScenePointer>;androidx.c... ()
#63	0x1029182d0 in kfun:androidx.compose.ui.scene.ComposeScene#sendPointerEvent(androidx.compose.ui.input.pointer.PointerEventType;kotlin.collections.List<androidx.compose.ui.scene.ComposeScenePointer>;androidx.compo... ()
#64	0x1029182d0 in kfun:androidx.compose.ui.scene.ComposeScene#sendPointerEvent$default(androidx.compose.ui.input.pointer.PointerEventType;kotlin.collections.List<androidx.compose.ui.scene.ComposeScenePointer>;androi... ()
#65	0x1029182d0 in kfun:androidx.compose.ui.scene.ComposeSceneMediator.object-2.onTouchesEvent#internal ()
#66	0x10292c66c in <inlined-out:<anonymous>> ()
#67	0x10292c66c in <inlined-out:let> ()
#68	0x10292c66c in kfun:androidx.compose.ui.window.InteractionUIView#objc:touchesBegan:withEvent: ()
#69	(null) in _6f72672e6a6574627261696e732e636f6d706f73652e75693a75692f6f70742f6275696c644167656e742f776f726b2f383339343731666333323931333563372f636f6d706f73652f75692f75692f7372632f75696b69744d61696e2f6b6f746c69... ()
#70	(null) in -[UIWindow _sendTouchesForEvent:] ()
#86	(null) in UIApplicationMain ()
#87	0x1022a32f0 in main at /Users/vinibarros/StudioProjects/BTPExperience/iosApp/iosApp/AppDelegate.swift:17
#88	(null) in start ()

`

**Comment by MatkovIvan** [comment]
@VdBarros There is no such version of Compose Multiplatform. Probably another confusion because of [this](https://youtrack.jetbrains.com/issue/KT-66613/)

**Comment by VdBarros** [comment]
> @VdBarros There is no such version of Compose Multiplatform. Probably another confusion because of [this](https://youtrack.jetbrains.com/issue/KT-66613/)

Oh, thats really confusing I haven't realised it. Thanks, im updating it right now, do not consider my last reply.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4531">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
